sudo: required

language: generic

services:
  - docker

before_install:
  - echo "Start creating an image with dockerfile on Travis!"
  - docker build -t basicpail93/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true basicpail93/docker-react-app -- --coverage

after_success:
  - echo "build success!"