sudo: required

language: generic

services:
  - docker

before_install:
  - echo "Start creating an image with dockerfile on Travis!"
  - docker build -t basicpail93/docker-ping-app -f Dockerfile .

script:
  - docker run -e CI=true basicpail93/docker-ping-app

after_success:
  - echo "build success!"