sudo: required

language: generic

services:
  - docker

before_install:
  - echo "Start creating an image with dockerfile on Travis!"
  - docker build -t basicpail93/docker-ping-app -f Dockerfile .

script:
  script:
  - echo "Running Docker container and checking status..."
  - docker run -e CI=true basicpail93/docker-ping-app sh -c "while true; do echo 'Docker is running...'; sleep 1; done"

after_success:
  - echo "build success!"