sudo: required

language: generic

services:
  - docker

before_install:
  - echo "Start creating an image with dockerfile on Travis!"
  - docker build -t basicpail/docker-ping-app -f Dockerfile .

script:
  - echo "Running Docker container!"
  - docker run -e CI=true basicpail/docker-ping-app

after_success:
  - echo "Build success!"